/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Hashan
 */
public class EmployeeMenu extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeMenu
     */
    public EmployeeMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Search = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        View = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JuserID = new javax.swing.JTextField();
        jusername = new javax.swing.JTextField();
        jFullname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jobCatego = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jGender = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jAddress = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jContact = new javax.swing.JTextField();
        Delete = new javax.swing.JToggleButton();
        Back = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        AddEmployee = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User ID", "Username", "Full Name", "Job Category", "Gender", "Address", "Contact"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 920, 161));

        jLabel1.setFont(new java.awt.Font("Cooper Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setText("Manage Employee");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 380, 50));

        Search.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        getContentPane().add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 176, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        View.setBackground(new java.awt.Color(204, 255, 204));
        View.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        View.setText("View Employees");
        View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewActionPerformed(evt);
            }
        });
        getContentPane().add(View, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 160, 30));

        Clear.setBackground(new java.awt.Color(204, 255, 204));
        Clear.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        getContentPane().add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 584, 143, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("User ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, 24));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Username");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, 70, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Full Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 70, 20));

        JuserID.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        JuserID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JuserIDActionPerformed(evt);
            }
        });
        getContentPane().add(JuserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 163, -1));

        jusername.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(jusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 410, 163, -1));

        jFullname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(jFullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 163, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Job Category");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, -1, -1));

        jobCatego.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(jobCatego, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, 163, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gender");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, -1, -1));

        jGender.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(jGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 163, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Address");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 490, -1, -1));

        jAddress.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(jAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 490, 163, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Contact");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, -1, -1));

        jContact.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jContactActionPerformed(evt);
            }
        });
        getContentPane().add(jContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, 163, -1));

        Delete.setBackground(new java.awt.Color(204, 255, 204));
        Delete.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, 161, 30));

        Back.setBackground(new java.awt.Color(255, 204, 204));
        Back.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 634, 67, 30));

        Update.setBackground(new java.awt.Color(204, 255, 204));
        Update.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        getContentPane().add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 584, 143, 30));

        Exit.setBackground(new java.awt.Color(255, 204, 204));
        Exit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 630, 71, 30));

        AddEmployee.setBackground(new java.awt.Color(204, 255, 204));
        AddEmployee.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        AddEmployee.setText("Add Employee");
        AddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmployeeActionPerformed(evt);
            }
        });
        getContentPane().add(AddEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 114, 161, 30));

        jLabel10.setBackground(new java.awt.Color(204, 255, 204));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/1113934-apples-wallpaper-1920x1200-ios.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-210, 0, 1200, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_ClearActionPerformed

    private void jContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jContactActionPerformed

    private void JuserIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JuserIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JuserIDActionPerformed
   static void AddRowToTable(Object[] dataRow)
    {
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.addRow(dataRow);
        
    }
    private void ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewActionPerformed
        String fileName = "Employee.txt";
File file = new File(fileName);

try {
    BufferedReader br = new BufferedReader(new FileReader(file));

    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

    // Clear existing rows from the table
    model.setRowCount(0);

    String line;
    while ((line = br.readLine()) != null) {
        String[] dataRow = line.split(" ");
        model.addRow(dataRow);
    }

        br.close();
    } catch (FileNotFoundException ex) {
        JOptionPane.showMessageDialog(this, "File not found: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    } catch (IOException ex) {
        JOptionPane.showMessageDialog(this, "Error reading file: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }                       
    }//GEN-LAST:event_ViewActionPerformed

     static void addRowToTable(Object[] dataRow)
    {
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.addRow(dataRow);
        
    }
    private void AddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmployeeActionPerformed
         
         ManageUser MU = new ManageUser();
        MU.setVisible(true);
        MU.pack();
        MU.setLocationRelativeTo(null);
        MU.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_AddEmployeeActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        DefaultTableModel tb2Model = (DefaultTableModel) jTable1.getModel();

    if (jTable1.getSelectedRowCount() == 1) {
        int selectedRow = jTable1.getSelectedRow();
        tb2Model.removeRow(selectedRow);
        
        // Delete the corresponding row from the text file
        deleteRowFromFi1e(selectedRow);
    } else {
        if (jTable1.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Table is Empty");
        } else {
            JOptionPane.showMessageDialog(this, "Please select a single Row to delete");
        }
    }
    }//GEN-LAST:event_DeleteActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        
    DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
    TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(tblModel);
    jTable1.setRowSorter(sorter);

    // Get the text to be searched from the Search field
    String searchText = Search.getText().trim();

    if (searchText.isEmpty()) {
        // If the search text is empty, show an error message and return
        JOptionPane.showMessageDialog(this, "Please enter something to search.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    } else {
        try {
            // Use RowFilter to perform case-insensitive regex filtering
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + searchText));
        } catch (java.util.regex.PatternSyntaxException ex) {
            // Handle regex pattern syntax errors, if any
            JOptionPane.showMessageDialog(this, "Invalid search pattern.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }


    }//GEN-LAST:event_SearchActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
             DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
    if (jTable1.getSelectedRowCount() == 1) {
        // Get the selected row index
        int selectedRowIndex = jTable1.getSelectedRow();


        // Get the updated values from the text fields
        int UserID = Integer.parseInt(JuserID.getText());
        String Username = jusername.getText();
        String FullName = jFullname.getText();
        String JobCategory = jobCatego.getText();
        String Gender = jGender.getText();
        String Address = jAddress.getText();
        int Contact = Integer.parseInt(jContact.getText());

        // Set the updated values in the table
        tblModel.setValueAt(UserID, selectedRowIndex, 0);
        tblModel.setValueAt(Username, selectedRowIndex, 1);
        tblModel.setValueAt(FullName, selectedRowIndex, 2);
        tblModel.setValueAt(JobCategory, selectedRowIndex, 3);
        tblModel.setValueAt(Gender, selectedRowIndex, 4);
        tblModel.setValueAt(Address, selectedRowIndex, 5);
        tblModel.setValueAt(Contact, selectedRowIndex, 6);

        // Save the updated data back to the "Employee.txt" file
        String fileName = "Employee.txt";
        File file = new File(fileName);
        try {
            FileWriter writer = new FileWriter(file);

            for (int row = 0; row < tblModel.getRowCount(); row++) {
                for (int col = 0; col < tblModel.getColumnCount(); col++) {
                    writer.write(tblModel.getValueAt(row, col).toString() + " ");
                }
                writer.write(System.getProperty("line.separator"));
            }

            writer.close();
            JOptionPane.showMessageDialog(this, "Data updated and saved successfully.");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error saving data to file: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        if (jTable1.getSelectedRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Table is Empty");
        } else {
            JOptionPane.showMessageDialog(this, "Please Select a single Row to Update");
        }
    }
    }//GEN-LAST:event_UpdateActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
          // Get the selected row index
    int selectedRowIndex = jTable1.getSelectedRow();
    
    // Set data to text fields from the selected row
    JuserID.setText(jTable1.getValueAt(selectedRowIndex, 0).toString());
    jusername.setText(jTable1.getValueAt(selectedRowIndex, 1).toString());
    jFullname.setText(jTable1.getValueAt(selectedRowIndex, 2).toString());
    jobCatego.setText(jTable1.getValueAt(selectedRowIndex, 3).toString());
    jGender.setText(jTable1.getValueAt(selectedRowIndex, 4).toString());
    jAddress.setText(jTable1.getValueAt(selectedRowIndex, 5).toString());
    jContact.setText(jTable1.getValueAt(selectedRowIndex, 6).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // Create a new instance of the Manager frame
    Manager manager = new Manager();
    
    // Close the current frame
    this.dispose();
    
    // Set the visibility of the manager frame to true
    manager.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed
private void deleteRowFromFi1e(int rowIndex) {
    try {
        File file = new File("Employee.txt");
        List<String> lines = Files.readAllLines(file.toPath());
        
        if (rowIndex >= 0 && rowIndex < lines.size()) {
            lines.remove(rowIndex);
            Files.write(file.toPath(), lines);
        }
    } catch (IOException e) {
        e.printStackTrace();
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEmployee;
    private javax.swing.JButton Back;
    private javax.swing.JButton Clear;
    private javax.swing.JToggleButton Delete;
    private javax.swing.JButton Exit;
    private javax.swing.JTextField JuserID;
    private javax.swing.JTextField Search;
    private javax.swing.JButton Update;
    private javax.swing.JButton View;
    private javax.swing.JTextField jAddress;
    private javax.swing.JTextField jContact;
    private javax.swing.JTextField jFullname;
    private javax.swing.JTextField jGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTable1;
    private javax.swing.JTextField jobCatego;
    private javax.swing.JTextField jusername;
    // End of variables declaration//GEN-END:variables

}
