/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App;

import Product.Product;
import Product.ProductDB;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hashan
 */
public class ManageProduct extends javax.swing.JFrame {
    ProductDB pdb= new ProductDB();
    /**
     * Creates new form ManageProduct
     */
    public ManageProduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPprice = new javax.swing.JTextField();
        JNoItems = new javax.swing.JTextField();
        JAdd = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ProType = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JPID = new javax.swing.JTextField();
        JPname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPprice.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(JPprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 214, 184, -1));

        JNoItems.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        JNoItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JNoItemsActionPerformed(evt);
            }
        });
        getContentPane().add(JNoItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 264, 184, -1));

        JAdd.setBackground(new java.awt.Color(255, 204, 204));
        JAdd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        JAdd.setText("Add");
        JAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JAddActionPerformed(evt);
            }
        });
        getContentPane().add(JAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 81, 30));

        Back.setBackground(new java.awt.Color(255, 204, 204));
        Back.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 320, 78, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Product ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Product Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 172, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Product Type");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 116, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Price");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 222, -1, -1));

        ProType.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ProType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProTypeActionPerformed(evt);
            }
        });
        getContentPane().add(ProType, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 112, 184, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("No Of Items");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 268, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Cooper Black", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 204));
        jLabel5.setText("Product Details");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 340, 39));

        JPID.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        JPID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPIDActionPerformed(evt);
            }
        });
        getContentPane().add(JPID, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 66, 184, -1));

        JPname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        JPname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPnameActionPerformed(evt);
            }
        });
        getContentPane().add(JPname, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 162, 184, 26));

        jLabel7.setBackground(java.awt.SystemColor.controlHighlight);
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/apple-logo-vortex.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 390, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JNoItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JNoItemsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JNoItemsActionPerformed
    
    
    private void JAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JAddActionPerformed
        // Check if any required fields are empty
    if (JPID.getText().isEmpty() || ProType.getText().isEmpty() || JPname.getText().isEmpty() ||
            JPprice.getText().isEmpty() || JNoItems.getText().isEmpty()) {

        JOptionPane.showMessageDialog(this, "Please fill in all the required fields.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    ProductMenu.AddRowsToTable(new Object[]{
            JPID.getText(),
            ProType.getText(),
            JPname.getText(),
            JPprice.getText(),
            JNoItems.getText(),

    });

    int ProductID = Integer.parseInt(JPID.getText());
    String ProductType = ProType.getText();
    String Productname = JPname.getText();
    String Price = JPprice.getText();
    int NoOfItems = Integer.parseInt(JNoItems.getText());

    Product p1 = new Product(ProductID, ProductType, Productname, Price, NoOfItems);
    String dataLine = ProductID + "," + ProductType + "," + Productname + "," + Price + "," + NoOfItems;
    saveDataToFile(dataLine);
    if (pdb.add(p1)) {
        JOptionPane.showMessageDialog(this, "Report Added");
    } else {
        JOptionPane.showMessageDialog(this, "Report can't be added");
    }
    }//GEN-LAST:event_JAddActionPerformed

     private void saveDataToFile(String dataLine) {
      int ProductID = Integer.parseInt(JPID.getText());
    String ProductType = ProType.getText();
    String Productname = JPname.getText();
    String Price = JPprice.getText();
    int NoOfItems = Integer.parseInt(JNoItems.getText());
    
    try {
        String fileName = "Product.txt"; // File name without full path
        FileWriter Writer = new FileWriter(fileName, true);
        Writer.write(ProductID + " " + ProductType + " " + Productname + " " + Price + " " + NoOfItems);
        Writer.write(System.getProperty("line.separator"));
        Writer.close();
        JOptionPane.showMessageDialog(null, "Success");
        setVisible(false);
    } catch (IOException ex) {
        JOptionPane.showMessageDialog(this, "Error saving data to file: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
 }
    
    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
      
    this.dispose();
    
    }//GEN-LAST:event_BackActionPerformed

    private void ProTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProTypeActionPerformed

    private void JPIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPIDActionPerformed

    private void JPnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton JAdd;
    private javax.swing.JTextField JNoItems;
    private javax.swing.JTextField JPID;
    private javax.swing.JTextField JPname;
    private javax.swing.JTextField JPprice;
    private javax.swing.JTextField ProType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
