/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App;

import Employee.Employee;
import Employee.EmployeeDB;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Hashan
 */
public class ManageUser extends javax.swing.JFrame {
    EmployeeDB edb= new EmployeeDB();
    /**
     * Creates new form ManageUser
     */
    public ManageUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JuserID = new javax.swing.JTextField();
        jusername = new javax.swing.JTextField();
        jFullname = new javax.swing.JTextField();
        jobCatego = new javax.swing.JTextField();
        jAddress = new javax.swing.JTextField();
        jGender = new javax.swing.JTextField();
        jContact = new javax.swing.JTextField();
        Add = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 118, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Full Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 164, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Job Category");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 202, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Gender");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 244, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Address");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 286, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Contact");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 332, -1, -1));

        JuserID.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        JuserID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JuserIDActionPerformed(evt);
            }
        });
        getContentPane().add(JuserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 76, 193, -1));

        jusername.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jusernameActionPerformed(evt);
            }
        });
        getContentPane().add(jusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 118, 193, -1));

        jFullname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jFullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFullnameActionPerformed(evt);
            }
        });
        getContentPane().add(jFullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 193, -1));

        jobCatego.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(jobCatego, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 202, 193, -1));

        jAddress.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(jAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 286, 193, -1));

        jGender.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGenderActionPerformed(evt);
            }
        });
        getContentPane().add(jGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 244, 193, -1));

        jContact.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(jContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 328, 193, -1));

        Add.setBackground(new java.awt.Color(255, 204, 204));
        Add.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        getContentPane().add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 86, -1));

        Back.setBackground(new java.awt.Color(255, 204, 204));
        Back.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 403, 75, -1));

        jLabel8.setFont(new java.awt.Font("Cooper Black", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 204));
        jLabel8.setText("Employee Details");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 360, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/1113934-apples-wallpaper-1920x1200-ios.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, -20, 590, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFullnameActionPerformed

    private void jusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jusernameActionPerformed

    private void JuserIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JuserIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JuserIDActionPerformed

    private void jGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jGenderActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
   // Check if any required fields are empty
if (JuserID.getText().trim().isEmpty() || jusername.getText().trim().isEmpty() || jFullname.getText().trim().isEmpty() ||
        jobCatego.getText().trim().isEmpty() || jGender.getText().trim().isEmpty() || jAddress.getText().trim().isEmpty() ||
        jContact.getText().trim().isEmpty()) {

    JOptionPane.showMessageDialog(this, "Please fill in all the required fields.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

EmployeeMenu.AddRowToTable(new Object[]{
        JuserID.getText(),
        jusername.getText(),
        jFullname.getText(),
        jobCatego.getText(),
        jGender.getText(),
        jAddress.getText(),
        jContact.getText(),
});

int UserID = Integer.parseInt(JuserID.getText().trim());
String Username = jusername.getText().trim();
String FullName = jFullname.getText().trim();
String JobCategory = jobCatego.getText().trim();
String Gender = jGender.getText().trim();
String Address = jAddress.getText().trim();
int Contact = Integer.parseInt(jContact.getText().trim());

Employee e1 = new Employee(UserID, Username, FullName, JobCategory, Gender, Address, Contact) {
    @Override
    protected void displayInformation() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
};
String dataLine = UserID + "," + Username + "," + FullName + "," + JobCategory + "," + Gender + "," + Address + "," + Contact;
saveDataToFile(dataLine);

if (edb.add(e1)) {
    JOptionPane.showMessageDialog(this, "Report Added");
} else {
    JOptionPane.showMessageDialog(this, "Report can't be added");
}
    }//GEN-LAST:event_AddActionPerformed
private void saveDataToFile(String dataLine) {
     int UserID = Integer.parseInt(JuserID.getText());
    String Username = jusername.getText();
    String FullName = jFullname.getText();
    String JobCategory  = jobCatego.getText();
    String Gender =  jGender.getText();
    String Address= jAddress.getText();
    int Contact = Integer.parseInt(jContact.getText());
    
    try {
        String fileName = "Employee.txt"; // File name without full path
        FileWriter Writer = new FileWriter(fileName, true);
        Writer.write(UserID + " " + Username  + " " + FullName + " " + JobCategory  + " " + Gender+" "+Address+" "+Contact);
        Writer.write(System.getProperty("line.separator"));
        Writer.close();
        JOptionPane.showMessageDialog(null, "Success");
        setVisible(false);
    } catch (IOException ex) {
        JOptionPane.showMessageDialog(this, "Error saving data to file: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
 }
    
    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
     
    this.dispose();
    
    
    }//GEN-LAST:event_BackActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Back;
    private javax.swing.JTextField JuserID;
    private javax.swing.JTextField jAddress;
    private javax.swing.JTextField jContact;
    private javax.swing.JTextField jFullname;
    private javax.swing.JTextField jGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jobCatego;
    private javax.swing.JTextField jusername;
    // End of variables declaration//GEN-END:variables
}
