/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App;

/**
 *
 * @author Hashan
 */
public class Manager extends javax.swing.JFrame {

    /**
     * Creates new form Manager
     */
    public Manager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Product = new javax.swing.JToggleButton();
        Employee = new javax.swing.JToggleButton();
        Exit = new javax.swing.JToggleButton();
        logout = new javax.swing.JToggleButton();
        AccountManager = new javax.swing.JButton();
        AccountCashier = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Elephant", 1, 36)); // NOI18N
        jLabel1.setForeground(java.awt.SystemColor.control);
        jLabel1.setText("Welcome To AppleiStore");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 480, 50));

        Product.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Product.setText("Product");
        Product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductActionPerformed(evt);
            }
        });
        getContentPane().add(Product, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 269, -1));

        Employee.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Employee.setText("Employee");
        Employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeActionPerformed(evt);
            }
        });
        getContentPane().add(Employee, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 269, -1));

        Exit.setBackground(new java.awt.Color(255, 204, 204));
        Exit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, 91, -1));

        logout.setBackground(new java.awt.Color(255, 204, 204));
        logout.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 82, -1));

        AccountManager.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        AccountManager.setText("Create Account for Manager");
        AccountManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountManagerActionPerformed(evt);
            }
        });
        getContentPane().add(AccountManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 269, -1));

        AccountCashier.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        AccountCashier.setText("Create Account for Cashier");
        AccountCashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountCashierActionPerformed(evt);
            }
        });
        getContentPane().add(AccountCashier, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 269, -1));

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/apple-logo-vortex.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-210, 0, 790, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
       System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void EmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeActionPerformed
         EmployeeMenu em = new EmployeeMenu();
        
    // Close the current frame
    this.dispose();
    
    // Set the visibility of the EmployeeMenu frame to true
    em.setVisible(true);
    }//GEN-LAST:event_EmployeeActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // Create a new instance of the Start frame
    Start startFrame = new Start();
    
    // Close the current frame
    this.dispose();
    
    // Set the visibility of the Start frame to true
    startFrame.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void AccountManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountManagerActionPerformed
   RegisterManager registerManager = new RegisterManager();
        
    // Close the current frame
    this.dispose();
    
    // Set the visibility of the RegisterManager frame to true
    registerManager .setVisible(true);
    }//GEN-LAST:event_AccountManagerActionPerformed

    private void ProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductActionPerformed
        // TODO add your handling code here:
        ProductMenu pm=new ProductMenu();
    
    // Close the current frame
    this.dispose();
    
    // Set the visibility of the ProductMenu frame to true
    pm.setVisible(true);
    }//GEN-LAST:event_ProductActionPerformed

    private void AccountCashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountCashierActionPerformed
       RegisterCashier registerCashier= new RegisterCashier();
        
    
    // Close the current frame
    this.dispose();
    
    // Set the visibility of the RegisterCashier frame to true
    registerCashier.setVisible(true);
    }//GEN-LAST:event_AccountCashierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccountCashier;
    private javax.swing.JButton AccountManager;
    private javax.swing.JToggleButton Employee;
    private javax.swing.JToggleButton Exit;
    private javax.swing.JToggleButton Product;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToggleButton logout;
    // End of variables declaration//GEN-END:variables

    
    
}
